### ISSUE TITLE
Build successful, however the AntMonitor app keeps stopping in the emulator of Android Studio.

### ISSUE THREAD

**Issue by dabeiz** [UCI-Networking-Group/AntMonitor#7]
Hi there!

I am trying to install this app as a preliminary for OVRSeen project, however, I met an error.
Even though I can successfully build this project in Android Studio and install it in the emulator, it keeps stopping when I try to use it.
 
The configuration of the AntMonitor project in Android Studio is as follows:
Android Studio: Android Studio Chipmunk | 2021.2.1 Patch 2
Emulator: Android 10.0 x86; API 29;
Gradle JDK: default 11.0.12 (I also tried version 1.8.0_321)
Android Gradle Plugin Version: 4.0.0
Gradle Version: 6.1.1

Thanks!

p.s. I record how this app crashes and upload this video to google drive https://drive.google.com/file/d/1Ktq4ANXE7SGjtk_AOEqelDtExu293l5F/view?usp=sharing

**Comment by nshuba** [comment]
Hey there and thanks for your interest!

For crashes, it would be helpful to know the stack trace from the logcat output. I'll also try to reproduce in the next few days.

**Comment by dabeiz** [comment]
Hi, I re-run the project and export some of the Logcat(Debug) when the app crashes.
see https://drive.google.com/file/d/1EvGD9Ph85J9XsZ_d-RXwmlorWwXl9JuT/view?usp=sharing 
Btw, will an apk file of AntMonitor that can be directly and successfully installed in Oculus Quest be available?

**Comment by nshuba** [comment]
Ok, I took a look at the logs and the video. Did AntMonitor ever ask for any permissions to be granted? It looks like it's missing the location permission. If it didn't ask, you can try manually allowing access from Android Settings --> Apps --> AntMonitor --> Permissions. Could you try granting all permissions and let me know if it still crashes?

Some background: the permissions AntMonitor requests are used to look for PII within the captured network traffic. Of course, ideally, the app should still function without these permissions, but I haven't had time to polish that part out.

Regarding the APK: my initial thoughts were that folks may want to modify AntMonitor (e.g. enable TLS interception and collect all apps' traffic by default) before using it. Let me think about providing an APK - it's true that that will make it easier for folks to get started.

**Comment by dabeiz** [comment]
Thanks for your help! 

The good news is that, after I manually grant all the permissions to AntMonitor on the emulator, it runs without crashing. 

The bad news is that AntMonitor still crashes when I tried to run it in my Quest2. I upload the video and logcat to a folder in google drive [ https://drive.google.com/drive/folders/1_IPD34LJu17i4LOpDNfJ1OBLtnx7e6w3?usp=sharing | https://drive.google.com/drive/folders/1_IPD34LJu17i4LOpDNfJ1OBLtnx7e6w3?usp=sharing ] 
(Since AntMonitor is an "unknown sources" app in Quest2, so I can't find it and grant the permissions for it on the system setting page) 

It seems that AntMonitor can successfully install the CA certificate in Quest2, however, it failed to launch a VPN service. 


发件人: "Anastasia Shuba" ***@***.***> 
收件人: "UCI-Networking-Group/AntMonitor" ***@***.***> 
抄送: "dabeiz" ***@***.***>, "Author" ***@***.***> 
发送时间: 星期日, 2023年 2 月 12日 上午 9:15:53 
主题: Re: [UCI-Networking-Group/AntMonitor] Build successful, however the AntMonitor app keeps stopping in the emulator of Android Studio. (Issue #7) 

Ok, I took a look at the logs and the video. Did AntMonitor ever ask for any permissions to be granted? It looks like it's missing the location permission. If it didn't ask, you can try manually allowing access from Android Settings --> Apps --> AntMonitor --> Permissions. Could you try granting all permissions and let me know if it still crashes? 

Some background: the permissions AntMonitor requests are used to look for PII within the captured network traffic. Of course, ideally, the app should still function without these permissions, but I haven't had time to polish that part out. 

Regarding the APK: my initial thoughts were that folks may want to modify AntMonitor (e.g. enable TLS interception and collect all apps' traffic by default) before using it. Let me think about providing an APK - it's true that that will make it easier for folks to get started.

**Comment by nshuba** [comment]
Glad to hear it's working on the emulator! If you're not seeing the permission requests at first app launch, you are probably using an older version of AntMonitor? I fixed a bug with this a few months after the OVRSeen release: https://github.com/UCI-Networking-Group/AntMonitor/commit/d69fc79e30fbf2ff7f738a06842a50c59ac08738. Could you try with the latest AntMonitor code? I recommend uninstalling whatever version you have on Quest2 first and then installing the updated version to have a clean slate.

We should have updated the OVRSeen documentation to point to this fixed version - sorry about that! I'll work on creating a new release and updating the docs this weekend. I'll add an APK to the release as well :)

**Comment by mentoxska** [comment]
Hello, the app keeps crashing for me on Quest 2, after "Start logging" is pressed. Also had some errors in android studio to build the app.

**Comment by nshuba** [comment]
@mentoxska, are you running the latest AntMonitor version? Could you try with [this apk](https://github.com/UCI-Networking-Group/AntMonitor/releases/download/ovrseen_usenix/antmonitor-release.apk)? If there's still a crash, please open a new issue and add some logs from `adb logcat`. 

@dabeiz, I created a release with an APK: https://github.com/UCI-Networking-Group/AntMonitor/releases/tag/ovrseen_usenix
Since I haven't heard from you, I am closing this issue as it appears to have been caused by ungranted permissions, which has been fixed in newer AntMonitor versions.

**Comment by mentoxska** [comment]
> @mentoxska, are you running the latest AntMonitor version? Could you try with [this apk](https://github.com/UCI-Networking-Group/AntMonitor/releases/download/ovrseen_usenix/antmonitor-release.apk)? If there's still a crash, please open a new issue and add some logs from `adb logcat`.

Thank you, this apk worked for me :) would be nice to provide it somewhere for people with build problems

**Comment by nshuba** [comment]
Great, thanks for confirming! We updated the [OVRSeen documentation](https://github.com/UCI-Networking-Group/OVRseen/wiki/Traffic-Collection) to point to the APK. In this repo, people can easily find it in the releases section.
