### ISSUE TITLE
Android 12

### ISSUE THREAD

**Issue by juli1001** [UCI-Networking-Group/AntMonitor#8]
it's possible to use it in oculus quest 3? it has android 12

**Comment by nshuba** [comment]
Thanks for your interest! Unfortunately, Android 11 introduced some changes that broke AntMonitor's TLS decryption. You can try it without decryption and that might work.

If you need decryption, I suggest exploring https://github.com/emanuele-f/PCAPdroid instead. I had success with it on regular Android 12+ devices, but I have not tried it on Quests.
